version: '3.8'

services:
  kafka:
    image: bitnami/kafka
    restart: always
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      # 服务器内网ip:2181/kafka
      # 配置zookeeper管理kafka的路径
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk1:2182,zk1:2183"
      # PLAINTEXT://服务器内网ip:port
      # 把kafka的地址端口注册给zookeeper
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # 配置kafka的监听端口
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LOG_RETENTION_HOURS: 24
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000
    volumes:
      - D:/ProgramData/DockerDesktop/docker/kafka/data:/kafka
      #- D:/ProgramData/DockerDesktop/docker/kafka/etc/localtime:/etc/localtime
    networks:
      - mynet


  kafka-ui:
    image: provectuslabs/kafka-ui:master
    restart: always
    container_name: kafka-ui
    ports:
      - "9099:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kaka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zk1:2181,zk1:2182,zk1:2183"
    networks:
      - mynet

volumes:
  mydata:
    external: true
networks:
  mynet:
    driver: bridge
